/*
 * Copyright (c) 2022-2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import UIAbility from '@ohos.app.ability.UIAbility';
import { BusinessError } from '@ohos.base';
import { logger } from '@ohos/details-page-component';
import notificationManager from '@ohos.notificationManager';
import window from '@ohos.window';

const TAG: string = 'MainAbility';
const INDEX_UIL: string = 'pages/Index';

export default class MainAbility extends UIAbility {
  onCreate(): void {
    logger.info(TAG, 'onCreate');
    this.ensureNotificationEnabled();
  }

  async ensureNotificationEnabled(): Promise<void> {
    try {
      if (!notificationManager.isNotificationEnabledSync()) {
        await notificationManager.requestEnableNotification(this.context);
      }
    } catch (error) {
      const businessError: BusinessError = error as BusinessError;
      logger.info(TAG, `ensureNotificationEnabled failed: ${JSON.stringify(businessError)}`);
    }
  }

  onDestroy(): void {
    logger.info(TAG, 'onDestroy');
  }

  onWindowStageCreate(windowStage: window.WindowStage): void {
    // Main window is created, set main page for this ability
    logger.info(TAG, 'onWindowStageCreate');

    windowStage.loadContent(INDEX_UIL);
  }

  onWindowStageDestroy(): void {
    // Main window is destroyed, release UI related resources
    logger.info(TAG, 'onWindowStageDestroy');
  }

  onForeground(): void {
    // Ability has brought to foreground
    logger.info(TAG, 'MainAbility onForeground');
  }

  onBackground(): void {
    // Ability has back to background
    logger.info(TAG, 'onBackground');
  }
}
